"use client";

import { BertrandCanvas, type BertrandCanvasHandle } from "@/components/bertrand/BertrandCanvas";
import { Button } from "@/components/ui/Button";
import { StatCounter } from "@/components/ui/StatCounter";
import {
  generateBatch,
  METHOD_DESCRIPTION,
  METHOD_LABEL,
  THEORETICAL_PROBABILITY,
  type BertrandMethod,
} from "@/lib/simulations/bertrand";
import { useEffect, useRef, useState } from "react";

const METHODS: BertrandMethod[] = ["endpoints", "radius", "midpoint"];
const PRESETS = [1, 100, 1_000, 10_000];
const REVEAL_DURATION_MS = 1400;

export function BertrandExperiment() {
  const [method, setMethod] = useState<BertrandMethod>("endpoints");
  const [running, setRunning] = useState(false);
  const [runSize, setRunSize] = useState<number | null>(null);
  const [total, setTotal] = useState(0);
  const [longerCount, setLongerCount] = useState(0);
  const canvasRef = useRef<BertrandCanvasHandle>(null);
  const frameRef = useRef<number | null>(null);

  useEffect(() => {
    return () => {
      if (frameRef.current) cancelAnimationFrame(frameRef.current);
    };
  }, []);

  function reset() {
    if (frameRef.current) cancelAnimationFrame(frameRef.current);
    setRunning(false);
    setRunSize(null);
    setTotal(0);
    setLongerCount(0);
    canvasRef.current?.reset();
  }

  function selectMethod(next: BertrandMethod) {
    reset();
    setMethod(next);
  }

  function run(n: number) {
    const canvas = canvasRef.current;
    if (!canvas) return;
    if (frameRef.current) cancelAnimationFrame(frameRef.current);

    const batch = generateBatch(method, canvas.radius, n);
    let revealed = 0;
    let longer = 0;
    let start: number | null = null;

    setRunSize(n);
    setRunning(true);

    function tick(now: number) {
      if (start === null) start = now;
      const elapsed = now - start;
      const targetRevealed = Math.min(
        n,
        Math.max(1, Math.ceil((elapsed / REVEAL_DURATION_MS) * n)),
      );

      while (revealed < targetRevealed) {
        const chord = batch[revealed];
        canvas!.drawChord(chord);
        if (chord.longerThanSide) longer++;
        revealed++;
      }

      setTotal(revealed);
      setLongerCount(longer);

      if (revealed < n) {
        frameRef.current = requestAnimationFrame(tick);
      } else {
        setRunning(false);
      }
    }

    frameRef.current = requestAnimationFrame(tick);
  }

  const percentage = total > 0 ? (longerCount / total) * 100 : 0;
  const theoretical = THEORETICAL_PROBABILITY[method] * 100;

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap gap-3">
        {METHODS.map((m) => (
          <Button
            key={m}
            variant={m === method ? "primary" : "secondary"}
            disabled={running}
            onClick={() => selectMethod(m)}
          >
            {METHOD_LABEL[m]}
          </Button>
        ))}
      </div>

      <p className="text-sm text-muted">
        <strong className="text-foreground">{METHOD_LABEL[method]}:</strong>{" "}
        {METHOD_DESCRIPTION[method]}
      </p>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[440px_1fr]">
        <BertrandCanvas ref={canvasRef} />

        <div className="flex flex-col gap-5">
          <div className="flex flex-wrap items-center gap-3">
            {PRESETS.map((n) => (
              <Button
                key={n}
                variant={runSize === n ? "primary" : "secondary"}
                disabled={running}
                onClick={() => run(n)}
              >
                Draw {n.toLocaleString()}
              </Button>
            ))}
            <Button variant="ghost" size="sm" disabled={running} onClick={reset}>
              Clear
            </Button>
          </div>

          {runSize !== null ? (
            <>
              <div className="rounded-2xl border border-border bg-background-elevated p-5">
                <p className="mb-1 text-xs uppercase tracking-wider text-[color:var(--color-expect-2)]">
                  Longer than the triangle&apos;s side
                </p>
                <p className="font-mono text-3xl tabular-nums">
                  <StatCounter value={percentage} format={(v) => `${v.toFixed(1)}%`} />
                </p>
                <p className="mt-2 font-mono text-xs text-muted">
                  n = {total.toLocaleString()} · theoretical limit: {theoretical.toFixed(1)}%
                </p>
              </div>

              <p className="text-sm text-muted">
                Cyan chords are longer than the triangle&apos;s side; coral chords are shorter.
                Every chord here was generated by the{" "}
                <strong className="text-foreground">{METHOD_LABEL[method].toLowerCase()}</strong>{" "}
                method — switch methods above and the same &ldquo;pick a random chord&rdquo;
                instruction converges to a completely different long-run percentage.
              </p>
            </>
          ) : (
            <div className="flex h-full min-h-32 items-center rounded-2xl border border-border bg-background-elevated p-5 text-sm text-muted">
              Pick a method above, then draw some chords to watch the percentage settle.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
